name = "img"
main = "data.js"

compatibility_date = "2025-02-16"


[observability]
enabled = true

[site]
bucket = "./"  # Direktori tempat file WASM berada

compatibility_flags = [ "nodejs_compat" ]

[[imports]]
module = "@jsquash/jpeg"
url = "https://esm.sh/@jsquash/jpeg@0.4.1"



