name = "img"
main = "data.js"

compatibility_date = "2025-02-16"


[observability]
enabled = true

[site]
bucket = "./"  # Direktori tempat file WASM berada

[build]
command = "npx esbuild data.js --bundle --outdir=dist --loader:.wasm=wasm"

[vars]
WASM_FILE = "djpeg-static.wasm"
