name = "img"
main = "data.js"

compatibility_date = "2025-02-16"


[observability]
enabled = true

[site]
bucket = "./"  # Direktori tempat file WASM berada

[vars]
DJPEG_STATIC = "./djpeg-static.js"

[wasm_modules]
MODUL = "modul.wasm"


